### ISSUE TITLE
Icons no longer a feature?

### ISSUE THREAD

**Issue by rrahim** [amiyasahu/q2a-breadcrumbs#10]
I've used some of the earlier versions and the icons were an awesome touch to this already amazing plugin.
I wanted to know if Icons are currently supported or if they ever will be supported again?

**Comment by amiyasahu** [comment]
Some people liked the icons but most of my users did not use the icons feature . So when I rewritten this in a better way to achive good performance , I dropped the icons feature .

**Comment by rrahim** [comment]
I'm grateful for the response and your excellent work on this plugin.
I just may add the icons into this plugin if you don't intend to do so yourself (using your past versions as a reference).

**Comment by amiyasahu** [comment]
in the newer version it is more easy than the earlier version .

You can go through this class file - https://github.com/amiyasahu/q2a-breadcrumbs/blob/master/inc/Ami_Breadcrumb.php

All the best .

**Comment by rrahim** [comment]
Thanks alot for the  info :)
