### ISSUE TITLE
extra slash (/) or slashes on the wrong places

### ISSUE THREAD

**Issue by truthonlytruth11** [amiyasahu/q2a-breadcrumbs#13]
![untitled-1](https://cloud.githubusercontent.com/assets/9207408/11074202/fe7adba6-87b3-11e5-99ff-5c583b63c657.jpg)
It happens only at footer
Header is working just fine...
Theme: SnowFlat
version: 1.7.1
breadcrumb version: 1.5.1

**Comment by amiyasahu** [comment]
Do you have the breadcrumbs at one place or at multiple places ?

**Comment by truthonlytruth11** [comment]
2 places
Header and footer

**Comment by amiyasahu** [comment]
can you put your website link where you are getting the error .

**Comment by truthonlytruth11** [comment]
Sorry, I have removed your plugin,
Thanks

**Comment by truthonlytruth11** [comment]
Hi Amiyasahu,
I have turned your app on and tested couple things and find out this:

I have realized that only happens when you pick 
Location:
Breadcrumbs - Full width - Below footer

if I choose
Breadcrumbs - Full width - Below content
It works...

Thanks

Something to do with footer code or another app is interfering with your app

**Comment by amiyasahu** [comment]
I have tested and it works fine in latest version of snow flat theme
