### ISSUE TITLE
schema.org use?

### ISSUE THREAD

**Issue by yerbol89** [amiyasahu/q2a-breadcrumbs#16]
Bro why do not use in breadcrumbs <ol itemscope itemtype="http://schema.org/BreadcrumbList">
vs <span
itemscope itemtype="http://data-vocabulary.org/Breadcrumb">

**Comment by amiyasahu** [comment]
Already using this - 
https://github.com/amiyasahu/q2a-breadcrumbs/blob/master/inc/Ami_BreadcrumbElement.php#L50
