### ISSUE TITLE
How to disable text overflow hidden in Breadcrumb Plugin ?

### ISSUE THREAD

**Issue by bahador1975** [amiyasahu/q2a-breadcrumbs#18]
Hi 

How can I show the complete question title in breadcrumb plugin and ignore showing " ... "

![capture](https://cloud.githubusercontent.com/assets/26009674/23312116/837c50a0-fa86-11e6-907b-b649679d6e90.PNG)

**Comment by amiyasahu** [comment]
You can disable `Truncate title in breadcrumb` in Plugin Options.
