### ISSUE TITLE
Schema error

### ISSUE THREAD

**Issue by rajakoppula** [amiyasahu/q2a-breadcrumbs#19]
error : url A value for the url field is required.

This error shows to all urls like cat, question and tags

See the image : https://ibb.co/mQ6TFQ

Regards,
Raja.

**Comment by chongshengdz** [comment]
i have the same problem,@amiyasahu please help fix the problem

**Comment by chongshengdz** [comment]
after checking the code,i found the solution.
go to q2a-breadcrumbs/inc/Ami_BreadcrumbElement.php
change
'breadcrumb_structure_nolink' => '<li {{class}} itemscope itemtype="http://data-vocabulary.org/Breadcrumb" ><span itemprop="title"> {{text}} </span></li>',
to
'breadcrumb_structure_nolink' => '<li {{class}} itemscope itemtype="http://data-vocabulary.org/Breadcrumb" ><a href="{{url}}" itemprop="url" > <span itemprop="title"> {{text}} </span></a></li>',

**Comment by amiyasahu** [comment]
@chongshengdz What is the difference between these two lines? they look identical.
