### ISSUE TITLE
sub category order

### ISSUE THREAD

**Issue by srcnsrcn** [amiyasahu/q2a-breadcrumbs#23]
sub category order is wrong
Category: Home > Accessories -> Headphones

Breadcrumb: Home > Headphones -> Accessories

**Comment by srcnsrcn** [comment]
Ami_Breadcrumb.php Line:347

delete:
$category_details = $this->get_category_details( $categoryids );

add:
                    $temp_category_details = $this->get_category_details( $categoryids );
					$category_details = array();
					foreach($categoryids as $categoryid){
						$category_details[$categoryid] = $temp_category_details[$categoryid];
					}

**Comment by amiyasahu** [comment]
Which version are you using?
