### ISSUE TITLE
XSS vector in Question Page Breadcrump Generator

### ISSUE THREAD

**Issue by thierryzoller** [amiyasahu/q2a-breadcrumbs#24]
In Ami_Breadcrumb.php you are taking user generated content without any input validation.

  $q_title = @$question_page['raw']['title'];

You could add 
"	$q_title = htmlspecialchars($q_title, ENT_QUOTES, 'UTF-8');" afterwards to solve this.

**Comment by thierryzoller** [comment]
https://github.com/amiyasahu/q2a-breadcrumbs/blob/master/inc/Ami_BreadCrumbOptions.php

Note: This issue originally was discovered by Steve Ehleringer. (Credit)

**Comment by thierryzoller** [comment]
The best place to patch would be to sanitze at Ami_BreadcrumbElement.php, see here

```
        public function get()
        {
            $breadcrumb_structure = qa_opt( q2a_breadcrumbs_admin::NO_LINK_AT_LAST_ELEM ) && $this->is_last_elem() ?
                $this->breadcrumb_structure_nolink
                : $this->breadcrumb_structure;
		    
			$test = htmlspecialchars($this->text);
            
			return strtr( $breadcrumb_structure, array(
                '{{class}}' => $this->class,
                '{{url}}'   => $this->url,
                '{{text}}'  => $test,
            ) );
        }
```

**Comment by amiyasahu** [comment]
I will fix this issue as soon as I can.

**Comment by svivian** [comment]
FYI you can use the `qa_html` function for this.

**Comment by amiyasahu** [comment]
@thierryzoller , I have fixed this in the dev branch. Let me know if you are still facing the issue.

**Comment by thierryzoller** [comment]
The ‘search’ function has the same issue - would advise to ensure all output is verified.

**Comment by amiyasahu** [comment]
Yes it fixes the search function as well.
